M48
; DRILL file {KiCad 9.0.7} date 2026-05-05T11:45:51-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-05T11:45:51-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X175.745Y-94.81
X175.745Y-100.59
T2
X170.55Y-76.7
X170.55Y-79.7
X212.5Y-102.0
X215.5Y-102.0
M30
