M48
; DRILL file {KiCad 9.0.7} date 2026-04-28T11:46:44-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-28T11:46:44-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X116.25Y-56.375
X116.25Y-61.375
T2
X82.0Y-51.5
X82.0Y-54.5
T3
X77.0Y-43.0
X77.0Y-75.0
X119.0Y-43.0
X119.0Y-75.0
M30
